export type MetadataCardProps = {
  fileName: string,
  sizeOnDisk: number,
  photoDate: Date,
  photoTimezone: string,
  resolutionWidth: number,
  resolutionHeight: number,
  mimeType: string,
  cameraModel: string,
  lensModel: string,
  shutterCount: number,
  focalLength: number,
  iso: number,
  shutterSpeed: string,
  aperture: number,
}